name: App Template
on:
  workflow_dispatch:
    inputs:
      appname:
        description: 'appname'
        type: string
        required: true
        default: 'app123'
      rgname:
        description: 'Resource group name'
        type: string
        required: true
        default: 'github_test_rg'
      cluster_name:
        description: 'AKS Cluster name'
        type: string
        required: true
        default: 'aks12378678'
      namespace:
        description: 'Namespace to deploy app'
        type: string
        required: true
        default: 'myapp'
        
jobs:
  Build_and_Publish:
    runs-on: self-hosted
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: saikiran243275/githubactions:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  Deploy_on_docker:
    runs-on: self-hosted
    needs: Build_and_Publish
    steps:
      - name: Deploy on docker 
        run: |
         docker rm -f $(docker ps -a -q)
         docker run --name ${{ inputs.appname }} -p 5000 -d saikiran243275/githubactions:latest
         docker ps
         docker images
  Deploy_on_kubernetes:
    runs-on: self-hosted
    needs: Deploy_on_docker
    steps:
      - name: Set AKS Conext 
        uses: azure/aks-set-context@v1
        with:
            creds: '${{ secrets.AZURE_CREDENTIALS }}'
            resource-group: ${{ inputs.rgname }}
            cluster-name: ${{ inputs.cluster_name }}
        id: login
      - name: Create Namespace
        run: |
          namespacePresent='kubectl get namespace | grep ${{ inputs.namespace }} | wc -l'
          if [[ "$namespacePresent" != "0" ]]; then
            kubectl create namespace ${{ inputs.namespace }}
          fi   
      - name: Deploy to Kubernetes cluster 
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          namespace: ${{ inputs.namespace }}
          manifests: |
            manifests/deployment.yaml
            manifests/pod_defination.yaml
            manifests/service.yaml
          images: saikiran243275/githubactions:latest
          annotate-namespace: false
     
  
